steps:

#Installing the dependencies
- name: 'node:10'
  id: 'downtime-alert-service-build'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install
      npm run build -c
      ls -ltr
  dir: 'ingestion/downtime-alert-service'

#Building Image
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'downtime-alert-service-image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      ls -ltr
      gcloud builds submit --tag gcr.io/$PROJECT_ID/ccn-downtime-alert-service:$_VERSION .
  waitFor:
      - 'downtime-alert-service-build'
  dir: 'ingestion/downtime-alert-service'

# Deploy pushed image to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'downtime-alert-service-deploy'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud beta run deploy ccn-downtime-alert-service-dev --image=gcr.io/$PROJECT_ID/ccn-downtime-alert-service:$_VERSION --platform=managed --region=$_REGION --revision-suffix=$_VERSION
  waitFor:
    - 'downtime-alert-service-image'
  dir: 'ingestion/downtime-alert-service'

substitutions:
    #GCP Specific configuration. Please do'nt change anything
    _REGION: us-central1
    _GCS_BUCKET: ccn-build
    
    
    #Developers only change
    _VERSION: v1
    
logsBucket: 'gs://$_GCS_BUCKET/cloud_build_logs'
timeout: 1500s
